/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import proyecto2luis.BinaryHeap;
import proyecto2luis.Documento;
import proyecto2luis.TablaDispersion;

/**
 *
 * @author andre
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public static BinaryHeap bh;
    public static TablaDispersion td;
    public int segundos;
    public static Cronometro crono; 
    public Menu(BinaryHeap bh, TablaDispersion td, Cronometro c) {
        initComponents();
        this.bh = bh;
        this.td = td;
        this.segundos = 0;
        this.crono = c;
        actualizarCola();
        actualizar_usuarios();
    }
    
    public void actualizarCola(){
        this.cola.setText(bh.print(""));
    }
    
    public void actualizar_usuarios(){
        this.reg.setText(td.print_users(""));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        crear_usuario = new javax.swing.JButton();
        crear_doc = new javax.swing.JButton();
        enviar = new javax.swing.JButton();
        eliminar_usuario = new javax.swing.JButton();
        eliminar_doc = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cola = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        mostrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        reg = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        crear_usuario.setText("Crear Usuario");
        crear_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(crear_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        crear_doc.setText("Crear Documento");
        crear_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_docActionPerformed(evt);
            }
        });
        jPanel1.add(crear_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        enviar.setText("Mandar un Documento a la Impresora");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarActionPerformed(evt);
            }
        });
        jPanel1.add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        eliminar_usuario.setText("Eliminar Usuario");
        eliminar_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_usuarioActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        eliminar_doc.setText("Eliminar Documento");
        eliminar_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_docActionPerformed(evt);
            }
        });
        jPanel1.add(eliminar_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        cancelar.setText("Cancelar Impresion");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Opciones de Documento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Opciones de Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        cola.setColumns(20);
        cola.setRows(5);
        jScrollPane1.setViewportView(cola);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 290, 270));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Usuarios Registrados");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 100, -1, -1));

        mostrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mostrar.setText("Mostrar Árbol");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jPanel1.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        reg.setColumns(20);
        reg.setRows(5);
        jScrollPane2.setViewportView(reg);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1034, 130, 340, 460));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cola de impresión:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Opciones de Impresión");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, -1));

        jButton1.setText("Simular Impresión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 540, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        Arbol a = new Arbol(bh);
        a.setVisible(true);
        
    }//GEN-LAST:event_mostrarActionPerformed

    private void crear_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_usuarioActionPerformed
        // TODO add your handling code here:
        
        CrearUsuario cu = new CrearUsuario(td, bh);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_crear_usuarioActionPerformed

    private void eliminar_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_usuarioActionPerformed
        // TODO add your handling code here:
        EliminarUsuario eu = new EliminarUsuario(td, bh);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_eliminar_usuarioActionPerformed

    private void crear_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_docActionPerformed
        // TODO add your handling code here:
        segundos = crono.segundos;
        System.out.println(segundos);
        CrearDocumento cd = new CrearDocumento(td, segundos, bh);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_crear_docActionPerformed

    private void eliminar_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_docActionPerformed
        // TODO add your handling code here:
        EliminarDocumento ed = new EliminarDocumento(td, bh);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_eliminar_docActionPerformed

    private void enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarActionPerformed
        // TODO add your handling code here:
        EnviarDoc ev = new EnviarDoc(td,bh);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_enviarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        CancelarImpresion ci = new CancelarImpresion(td, bh);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(this.bh.heap[0]!= null){
        Documento impreso = this.bh.deleteMin();
        JOptionPane.showMessageDialog(rootPane, "Documento impreso: \n " + impreso.title + "." + impreso.type+"");
        actualizarCola();}else{
            JOptionPane.showMessageDialog(rootPane, "No hay documentos en la impresora");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(bh, td,crono).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextArea cola;
    private javax.swing.JButton crear_doc;
    private javax.swing.JButton crear_usuario;
    private javax.swing.JButton eliminar_doc;
    private javax.swing.JButton eliminar_usuario;
    private javax.swing.JButton enviar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextArea reg;
    // End of variables declaration//GEN-END:variables
}
